### ISSUE TITLE
halp.

### ISSUE THREAD

**Issue by Sloth-on-meth** [dessalines/reddit-banbot#1]
Goto https://github.com/dessalines/reddit-banbot for help
./run.sh: line 7: --subreddit: command not found
./run.sh: line 8: --threadSort: command not found
./run.sh: line 9: --userCommentSort: command not found
./run.sh: line 10: --badKarma: command not found
./run.sh: line 11: --banDuration: command not found
./run.sh: line 12: --save: command not found

**Comment by dessalines** [comment]
Im guessing your trying to run this from windows, where the forward slashes don't work. Try putting this all on one line. And make sure you follow all the instructions.

**Comment by slothonmeth** [comment]
Actually on Ubuntu headless, but I'll try that
